// Format all posts as markdown.
$(function() {
  // Setup marked.
  var renderer = new marked.Renderer();

  // Use <b> and <i> to match the standard mwf tags.
  renderer.strong = function(text) {
    return '<b>' + text + '</b>';
  };

  renderer.em = function(text) {
    return '<i>' + text + '</i>';
  };

  // Fix double linking generated by mwf.
  renderer.link = function(href, title, text) {
    href = href.replace(/.*href=&quot;(.*)&quot;&gt;.*/, "$1");
    return marked.Renderer.prototype.link.call(this, href, title, text);
  };

  // Fix double escaping in code blocks.
  renderer.code = function() {
	var result = marked.Renderer.prototype.code.apply(this, arguments);
	return result.replace(/&amp;/g, '&');
  };

  // Same for inline code.
  renderer.codespan = function(text) {
	text = text.replace(/&amp;/g, '&');
	return marked.Renderer.prototype.codespan.call(this, text);
  };

  marked.setOptions({
    renderer: renderer,
    breaks: true,
  });

  $('.pst, .msg, body[class$=_add] > .frm, body[class$=_edit] > .frm').find('.ccl:nth-child(2)').each(function() {
    var el, text;

    el = $(this);
    text = el.html();

    // Replace mwforum's <br>s with newlines so that paragraph detection works.
    text = text.replace(/<br>/g, '\n');
    // Remove blockquotes as they confuse marked.
    text = text.replace(/<blockquote><p>/g, '\n>');
    text = text.replace(/<\/p><\/blockquote>/g, '\n');
    // Remove the newline after the avatar as it shows up in the output.
    text = text.replace(/(<img class="ava" [^>]+>)\n/, '$1');

    el.html(marked(text));
    el.find('.ava').unwrap();
  });
});
